### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by CXiaoDing** [psyec1/Lipreading-PyTorch#5]
I run main.py, but I got an error. The error is as follows. Can someone here help me solve this problem? Thank you very much!
error：
Traceback (most recent call last):
File "/home/cxd/PycharmProjects/LRW/main.py", line 20, in <module>
    model.load_state_dict(torch.load(options["general"]["pretrainedmodelpath"]))
File "/home/cxd/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'trainedmodel.pt'

**Comment by sauravsolanki** [comment]
Ya Please, even I having same issue. @CXiaoDing  Did you get that how to solve it?

**Comment by chendeguang** [comment]
我现在也遇到了这个问题，请问你们有没有解决呢

**Comment by CXiaoDing** [comment]
哪个问题？不好意思，这个模型我好久没看了，有点不记得了





------------------ 原始邮件 ------------------
发件人: "chendeguang"<notifications@github.com>;
发送时间: 2019年4月12日(星期五) 晚上6:08
收件人: "psyec1/Lipreading-PyTorch"<Lipreading-PyTorch@noreply.github.com>;
抄送: "明天你好"<623955847@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [psyec1/Lipreading-PyTorch] about dataset (#5)




我现在也遇到了这个问题，请问你们有没有解决呢

**Comment by CXiaoDing** [comment]
在options.toml文件里，有个loadpretrainedmodel，改为false就行了

**Comment by CXiaoDing** [comment]
> Ya Please, even I having same issue. @CXiaoDing Did you get that how to solve it?

In the options.toml file, there is a parameter----loadpretrainedmodel, just change it to false

**Comment by fheilz** [comment]
@CXiaoDing Your solution works. @psyec1 Please close this issue.

**Comment by lymgoforit** [comment]
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    trainer = Trainer(options)
  File "/home/er607/桌面/lip/Lipreading-PyTorch-master/training.py", line 26, in __init__
    self.trainingdataset = LipreadingDataset(options["training"]["dataset"], "train")
  File "/home/er607/桌面/lip/Lipreading-PyTorch-master/data/dataset.py", line 31, in __init__
    self.label_list, self.file_list = self.build_file_list(directory, set)
  File "/home/er607/桌面/lip/Lipreading-PyTorch-master/data/dataset.py", line 9, in build_file_list
    labels = os.listdir(dir)
FileNotFoundError: [Errno 2] No such file or directory: '/udisk/pszts-ssd/AV-ASR-data/BBC_Oxford/lipread_mp4'
请问这个是要自己去下载lipread_mp4吗？

**Comment by lymgoforit** [comment]
> 
Traceback (most recent call last):
File "main.py", line 26, in 
trainer = Trainer(options)
File "/home/er607/桌面/lip/Lipreading-PyTorch-master/training.py", line 26, in init
self.trainingdataset = LipreadingDataset(options["training"]["dataset"], "train")
File "/home/er607/桌面/lip/Lipreading-PyTorch-master/data/dataset.py", line 31, in init
self.label_list, self.file_list = self.build_file_list(directory, set)
File "/home/er607/桌面/lip/Lipreading-PyTorch-master/data/dataset.py", line 9, in build_file_list
labels = os.listdir(dir)
FileNotFoundError: [Errno 2] No such file or directory: '/udisk/pszts-ssd/AV-ASR-data/BBC_Oxford/lipread_mp4'
请问这个是要自己去下载lipread_mp4吗？

**Comment by chendeguang** [comment]
是的，找中科院要。网址：http://vipl.ict.ac.cn/team.php?id=10------------------ Original ------------------

**Comment by lymgoforit** [comment]
@chendeguang 可以加微信聊吗，我有点小白，后期可能还有问题的，谢谢了

**Comment by lymgoforit** [comment]
@chendeguang 我微信15074943298

**Comment by lymgoforit** [comment]
@chendeguang 已经找到了并下载了  多谢

**Comment by PonderK** [comment]
@lymgoforit 您好，您能和我分享一下这份代码的数据集吗？上面的链接打不开了，麻烦您了

**Comment by YYingcute** [comment]
> @chendeguang 已经找到了并下载了 多谢
请问你是怎么找到下载的呢？方便的话可以告诉我一下吗

**Comment by YYingcute** [comment]
@lymgoforit 请问可以分享一下数据集吗？我的邮箱 ivory.yang.ying@gmail.com。感激。。

**Comment by cyz-951024** [comment]
> 你好，可以分享lipread_MP4文件吗，邮箱     henucyz@163.com    。万分感谢
